# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuobiSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_stamp', models.FloatField()),
                ('date_local', models.DateTimeField(null=True)),
                ('buy', models.FloatField()),
                ('high', models.FloatField()),
                ('last', models.FloatField()),
                ('low', models.FloatField()),
                ('sell', models.FloatField()),
                ('vol', models.FloatField()),
                ('open', models.FloatField()),
                ('symbol', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='okcoinspot',
            name='symbol',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='okcoinspot',
            name='date_local',
            field=models.DateTimeField(null=True),
        ),
    ]
