# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_auto_20170112_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='huobispot',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='okcoinspot',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='huobispot',
            name='date_local',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='okcoinspot',
            name='date_local',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
